apiVersion: v1
kind: Service
metadata:
  name: unode-dev-admin-frontend-service
  namespace: default
  labels:
    app: unode-dev-admin-frontend
spec:
  type: ClusterIP
  selector:
    app: unode-dev-admin-frontend
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
