apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: custom-alertmanager-config
  namespace: monitoring  # Replace with the namespace of your Alertmanager setup
  labels:
    release: prometheus
    alertmanagerConfig: instance
spec:
  route:
    groupBy:
      - alertname
    groupWait: 30s
    groupInterval: 1m
    repeatInterval: 1m
    receiver: webhook
    

  receivers:
    - name: webhook
      webhookConfigs:
        - url: 'http://unode-backend-service.default.svc.cluster.local:80/alert'
          sendResolved: true 
