apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-alerts-rules
  namespace: default
  labels:
    release: prometheus
spec:
  groups:
  - name: node-alerts
    rules:
    - alert: NodeDown
      expr: node_status == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Node {{ $labels.instance }} is down"
        description: "Node {{ $labels.instance }} on exporter unode-dev-exporter is down for more than 1 minute."
