apiVersion: v1
kind: Service
metadata:
  name: unode-backend-onboard-service
  namespace: default
  labels:
    app: unode-backend-onboard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: unode-backend-onboard
  type: ClusterIP
  sessionAffinity: None
