apiVersion: v1
items:
- apiVersion: acid.zalan.do/v1
  kind: postgresql
  metadata:
    name: unode-postgres
    namespace: default
  spec:
    databases:
      unode: postgres
    numberOfInstances: 2
    postgresql:
      version: "14"
    teamId: myteam
    users:
      postgres: []
    volume:
      size: 10Gi
  status:
    PostgresClusterStatus: Running
kind: List
metadata:
  resourceVersion: ""
